spring:
  profiles:
    active: local

  output:
    ansi:
      enabled: always

  devtools:
    add-properties: false

  jpa:
    database: mysql
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/sandbox
    username: catsriding
    password: catsriding

  data:
    redis:
      host: localhost
      port: 6379
      password: jZF3dcCERISFWVTvDt0zidKDJ8CcweUP
      timeout: 3000
      connect-timeout: 3000
      lettuce:
        shutdown-timeout: 5000
      repositories:
        enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace